include Makefile

CCompile=x86_64-elf-gcc
LdCompile=x86_64-elf-ld
ObjcopyCompile=llvm-objcopy
GccFlags=-m32 -fno-builtin -fno-stack-protector -mno-sse
GccFlags+=-w -Wno-error=implicit-function-declaration -Wno-error=int-conversion -nostdinc -nostdlib -fno-pic -fno-pie -g
